#!/bin/bash
rm -rf ../../../var/www/html/{*,.*}
cp -R ./frontend/dist/website2020/. ../../../var/www/html
cp ./frontend/.htaccess ../../../var/www/html
(cd ../../../var/www/html;sudo service apache2 restart)
